server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 200100
  jpa:
    show-sql: false
